import { Dashboard, Campaign, ImpactCard, Reminder, NamlefContent, Pledge, CollectorDashboard, User } from '../types';

export const MOCK_USER: User = {
  id: 'mock-user-1',
  full_name: 'Ahmed Hassan',
  nickname: 'Abu Yusuf',
  phone: '+254700000001',
  email: 'ahmed@example.com',
  country: 'Kenya',
  city: 'Nairobi',
  anonymous_publicly: false,
  is_collector: true,
  pledge_status: 'paid',
  donor_number: 42,
  badges: [
    { id: '1', name: 'First Pledge', description: 'Made your first pledge', icon: 'heart', tier: 'bronze', earned_at: '2024-01-15' },
    { id: '2', name: 'Faithful Donor', description: '3 consecutive months', icon: 'ribbon', tier: 'silver', earned_at: '2024-04-01' },
  ],
  created_at: '2024-01-10T10:00:00Z',
};

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Friday Challenge — June 2025',
    description: 'Join 200 donors every Friday in solidarity with Gaza. Together, small pledges create massive relief on the ground.',
    type: 'friday_challenge',
    target_donors: 200,
    current_donors: 142,
    is_active: true,
    is_urgent: false,
    start_date: '2025-06-01',
    created_at: '2025-06-01T00:00:00Z',
  },
  {
    id: 'camp-2',
    title: 'Emergency: Northern Gaza Displacement',
    description: '400 families have been displaced from northern Gaza and urgently need food, water, shelter, and medical supplies. Your USD 10 can provide immediate emergency relief to a family for three days.',
    type: 'emergency',
    target_donors: 500,
    current_donors: 287,
    target_amount: 5000,
    raised_amount: 2870,
    is_active: true,
    is_urgent: true,
    start_date: '2025-06-15',
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'camp-3',
    title: 'June Monthly Pledge Campaign',
    description: 'This month we are aiming to reach 1,000 active donors. Every pledge of USD 10 contributes to our monthly fund for food, medical care, and education in Gaza.',
    type: 'monthly',
    target_donors: 1000,
    current_donors: 634,
    is_active: true,
    is_urgent: false,
    start_date: '2025-06-01',
    end_date: '2025-06-30',
    created_at: '2025-06-01T00:00:00Z',
  },
  {
    id: 'camp-4',
    title: 'Medical Supplies for Al-Shifa Support',
    description: 'Funding critical medical equipment and supplies for field clinics serving displaced families in Gaza.',
    type: 'general',
    target_donors: 300,
    current_donors: 178,
    target_amount: 3000,
    raised_amount: 1780,
    is_active: true,
    is_urgent: false,
    start_date: '2025-05-20',
    created_at: '2025-05-20T00:00:00Z',
  },
];

export const MOCK_IMPACT_CARDS: ImpactCard[] = [
  {
    id: 'impact-1',
    title: '250 Food Packages Delivered',
    description: 'Last week, our network delivered 250 food packages to families in Rafah. Each package contains flour, rice, lentils, cooking oil, and canned goods — enough for a family of five for a week.',
    category: 'food',
    beneficiaries: 1250,
    location: 'Rafah, Gaza',
    date: '2025-06-20',
  },
  {
    id: 'impact-2',
    title: 'Medical Clinic Supplies Delivered',
    description: 'Through our emergency campaign, we funded surgical gloves, bandages, IV fluids, and antibiotics for a field clinic serving over 800 patients per day.',
    category: 'medical',
    beneficiaries: 800,
    location: 'Khan Younis, Gaza',
    date: '2025-06-18',
  },
  {
    id: 'impact-3',
    title: '50 Families Receive Emergency Shelter',
    description: 'Fifty displaced families received emergency tarpaulin shelters and blankets as temperatures dropped. Each shelter kit protects a family of 6 from the elements.',
    category: 'shelter',
    beneficiaries: 300,
    location: 'Northern Gaza',
    date: '2025-06-15',
  },
  {
    id: 'impact-4',
    title: 'Clean Water Tank Installed',
    description: 'A 10,000-litre water tank was installed in a displacement camp serving 2,000 people. Clean water access has been restored for the first time in weeks.',
    category: 'water',
    beneficiaries: 2000,
    location: 'Central Gaza',
    date: '2025-06-10',
  },
];

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    type: 'quran',
    arabic_text: 'وَمَن يَقْتُلْ مُؤْمِنًا مُّتَعَمِّدًا فَجَزَاؤُهُ جَهَنَّمُ',
    text: 'And whoever saves one — it is as if he had saved all mankind.',
    translation: 'Saving a life is equal to saving all of humanity.',
    explanation: 'This verse reminds us of the immeasurable value of every single human life. Your pledge today could help save families in Gaza.',
    source_reference: 'Quran 5:32',
    date: '2025-06-30',
  },
  {
    id: 'rem-2',
    type: 'hadith',
    arabic_text: 'الْمُسْلِمُ أَخُو الْمُسْلِمِ',
    text: 'The Muslim is the brother of the Muslim.',
    translation: 'He does not oppress him, he does not abandon him, and he does not despise him.',
    explanation: 'Brotherhood in Islam is not just a feeling — it is an action. When our brothers and sisters in Gaza suffer, we are called to respond.',
    source_reference: 'Sahih Muslim 2564',
    date: '2025-06-30',
  },
  {
    id: 'rem-3',
    type: 'dua',
    arabic_text: 'اللَّهُمَّ انْصُرِ الْمُسْتَضْعَفِينَ',
    text: 'O Allah, support the oppressed and the weak.',
    translation: 'Ya Allah, grant victory to the vulnerable in Palestine, Gaza, and all lands.',
    explanation: "Make this du'a after every prayer. It takes a second and could move mountains.",
    source_reference: "Traditional Du'a",
    date: '2025-06-30',
  },
  {
    id: 'rem-4',
    type: 'friday',
    arabic_text: 'يَوْمُ الجُمُعَةِ خَيْرُ يَوْمٍ',
    text: "It is Friday — the best day of the week.",
    translation: "The Prophet ﷺ said: 'The best day on which the sun has risen is Friday.'",
    explanation: "Use today's Jumu'ah to increase your sadaqah. Contribute your USD 10 pledge and invite a friend to join the Friday Challenge.",
    source_reference: 'Sunan Abu Dawud 1046',
    date: '2025-06-27',
  },
  {
    id: 'rem-5',
    type: 'motivation',
    text: 'A river is made of drops.',
    translation: 'Your USD 10 alone might seem small. But combined with 10,000 other pledges, it becomes a USD 100,000 relief operation.',
    explanation: "Don't underestimate your contribution. Every drop counts in the ocean of Gaza's needs.",
    date: '2025-06-30',
  },
];

export const MOCK_NAMLEF_CONTENT: NamlefContent[] = [
  {
    id: 'namlef-1',
    type: 'about',
    title: 'About NAMLEF',
    content: 'The National Muslim Leaders Forum (NAMLEF) is an umbrella body representing Muslim leaders and organisations across Eastern Africa. Established to coordinate Islamic humanitarian and advocacy work, NAMLEF mobilises communities for relief, education, and social justice causes. Family Pledge is our flagship programme responding to the crisis in Gaza.',
    author: 'NAMLEF Secretariat',
    author_title: 'National Muslim Leaders Forum',
    date: '2025-01-01',
  },
  {
    id: 'namlef-2',
    type: 'sheikh_message',
    title: 'A Message from the Sheikh',
    content: 'Bismillah ir-Rahman ir-Raheem. Dear brothers and sisters, the situation in Gaza weighs heavily on every Muslim heart. Our Prophet ﷺ said the believers are like one body — when one part suffers, the rest respond. Family Pledge is not charity alone; it is an expression of our brotherhood. I urge every family to join. USD 10 a month is less than a cup of coffee a week, but for a family in Gaza it means survival.',
    author: 'Sheikh Dr. Ibrahim Al-Amin',
    author_title: 'Chairperson, NAMLEF',
    date: '2025-06-01',
  },
  {
    id: 'namlef-3',
    type: 'voice_of_support',
    title: 'Voice of Support: Fatima from Nairobi',
    content: '"When I heard about Family Pledge, I thought: what can I, an ordinary mother in Nairobi, do for Gaza? Then I realised — I can pledge USD 10 a month. And if I convince 10 others in my masjid, that is USD 1,200 a year. Together we are not ordinary. Together we are powerful."',
    author: 'Fatima Mohamed',
    author_title: 'Donor & Community Mobiliser, Nairobi',
    date: '2025-05-15',
  },
  {
    id: 'namlef-4',
    type: 'introduction',
    title: 'Introduction to Family Pledge',
    content: 'Family Pledge was born from a simple idea: what if every Muslim family pledged just USD 10 a month for Gaza? With 1,000 families that is USD 10,000 monthly. With 10,000 families it is USD 100,000. The maths is simple. The impact is enormous. Every pledge is tracked, every contribution verified, and every dollar accounted for. This is transparent, community-driven relief.',
    date: '2025-01-15',
  },
];

export const MOCK_PLEDGE_STATUS = {
  pledge: {
    id: 'pledge-001',
    user_id: 'mock-user-1',
    amount: 10,
    currency: 'USD',
    status: 'paid' as const,
    month: 'June',
    year: 2025,
    contributed_at: '2025-06-05T09:30:00Z',
    reference: 'QKR7XNPK',
  },
  history: [
    { id: 'p1', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'June', year: 2025, contributed_at: '2025-06-05T09:30:00Z', reference: 'QKR7XNPK' },
    { id: 'p2', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'May', year: 2025, contributed_at: '2025-05-03T11:00:00Z', reference: 'MPF3BWKL' },
    { id: 'p3', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'April', year: 2025, contributed_at: '2025-04-07T08:15:00Z', reference: 'TXN9923X' },
    { id: 'p4', user_id: 'u1', amount: 10, currency: 'USD', status: 'missed' as const, month: 'March', year: 2025 },
    { id: 'p5', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'February', year: 2025, contributed_at: '2025-02-10T14:00:00Z', reference: 'BWK229JK' },
    { id: 'p6', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'January', year: 2025, contributed_at: '2025-01-12T10:00:00Z', reference: 'INV00142' },
  ],
};

export const MOCK_DASHBOARD: Dashboard = {
  user: MOCK_USER,
  pledge_status: 'paid',
  donor_number: 42,
  total_donors_today: 178,
  active_campaign: MOCK_CAMPAIGNS[0],
  emergency_appeal: MOCK_CAMPAIGNS[1],
  latest_reminder: MOCK_REMINDERS[0],
  latest_impact: MOCK_IMPACT_CARDS[0],
  monthly_progress: {
    target: 1000,
    current: 634,
  },
};

export const MOCK_COLLECTOR: CollectorDashboard = {
  collector_code: 'AHM-KE42',
  total_registered: 15,
  contributed_this_month: 10,
  pending_this_month: 5,
  invite_link: 'https://familypledge.org/join?code=AHM-KE42',
  circle_members: [
    { id: 'm1', display_name: 'Yusuf Omar', pledge_status: 'paid', joined_at: '2025-01-15T10:00:00Z' },
    { id: 'm2', display_name: 'Khadija Said', pledge_status: 'paid', joined_at: '2025-02-01T09:00:00Z' },
    { id: 'm3', display_name: 'Ibrahim Khalid', pledge_status: 'pending', joined_at: '2025-02-10T12:00:00Z' },
    { id: 'm4', display_name: 'Maryam Hassan', pledge_status: 'paid', joined_at: '2025-03-05T08:00:00Z' },
    { id: 'm5', display_name: 'Anon Donor', pledge_status: 'missed', joined_at: '2025-03-12T11:00:00Z' },
    { id: 'm6', display_name: 'Aisha Noor', pledge_status: 'paid', joined_at: '2025-04-01T14:00:00Z' },
    { id: 'm7', display_name: 'Bilal Ahmad', pledge_status: 'pending', joined_at: '2025-04-20T10:00:00Z' },
    { id: 'm8', display_name: 'Zaynab Juma', pledge_status: 'paid', joined_at: '2025-05-03T09:30:00Z' },
  ],
};
