import React, { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '../../constants/colors';
import AppButton from '../../components/AppButton';
import { submitFeatureRequest } from '../../services/api';

export default function RequestFeatureScreen(){const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[saving,setSaving]=useState(false);const submit=async()=>{if(title.trim().length<3||description.trim().length<10){Alert.alert('Add more detail','Give the feature a short title and explain what you would like Family Pledge to improve.');return;}setSaving(true);try{await submitFeatureRequest(title.trim(),description.trim());setTitle('');setDescription('');Alert.alert('Thank you','Your feature request has been recorded for the Family Pledge team.');}catch(e:any){Alert.alert('Could not send request',e.message||'Please try again.');}finally{setSaving(false);}};return <ScrollView style={styles.scroll} contentContainerStyle={styles.content}><View style={styles.hero}><Ionicons name="chatbox-ellipses-outline" size={32} color={Colors.goldLight}/><Text style={styles.h1}>Request a Feature</Text><Text style={styles.sub}>Tell the Family Pledge team what would make the app more useful.</Text></View><Text style={styles.label}>Feature title</Text><TextInput style={styles.input} value={title} onChangeText={setTitle} maxLength={160} placeholder="e.g. Family circle event calendar"/><Text style={styles.label}>What should it do?</Text><TextInput style={[styles.input,styles.area]} value={description} onChangeText={setDescription} multiline maxLength={3000} textAlignVertical="top" placeholder="Describe the problem and how you would like it to work."/><AppButton title="Send Feature Request" onPress={submit} loading={saving}/></ScrollView>}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:Colors.cream},content:{padding:16,paddingBottom:40},hero:{backgroundColor:Colors.primaryDark,borderRadius:24,padding:22,alignItems:'center',marginBottom:20},h1:{marginTop:8,fontSize:24,fontWeight:'900',color:Colors.white},sub:{marginTop:6,color:'rgba(255,255,255,.8)',textAlign:'center',lineHeight:19},label:{fontSize:13,fontWeight:'800',color:Colors.text.primary,marginBottom:6,marginTop:8},input:{backgroundColor:Colors.white,borderWidth:1,borderColor:Colors.border.medium,borderRadius:13,paddingHorizontal:13,paddingVertical:12,color:Colors.text.primary,marginBottom:10},area:{height:150}});
