'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Ban, Bot, CheckCircle2, History, Pause, Play, RotateCcw, XCircle } from 'lucide-react';
import toast from 'react-hot-toast';
import AdminLayout from '../../../components/AdminLayout';
import { approveAiTaskRun, createAiTask, dismissAiTaskRun, listAiTaskRuns, listAiTasks, retryAiTaskRun, runAiTaskNow, updateAiTask, type AiScheduleType, type AiTask, type AiTaskRun } from '../../../lib/aiWorkspaceApi';

const QUICK_TASKS=[
  {title:'Today’s admin briefing',instruction:'Summarize what needs Family Pledge admin attention today: contribution review, donor follow-ups, active campaigns, communications and waiting AI work.'},
  {title:'Missing pledge follow-up plan',instruction:'Summarize active Family Pledge pledges missing a confirmed or pending contribution this month and prepare a practical follow-up plan for admins.'},
  {title:'Friday content preparation',instruction:'Review approved Family Pledge Islamic reminder context and active Gaza campaigns, then prepare a Friday admin content plan for human review.'},
];

export default function TasksPage() {
  const[tasks,setTasks]=useState<AiTask[]>([]);const[runs,setRuns]=useState<AiTaskRun[]>([]);const[selectedTask,setSelectedTask]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState<string|null>(null);
  const[form,setForm]=useState({title:'',instruction:'',schedule_type:'manual',next_run_at:'',timezone:'Africa/Nairobi'});
  const load=async()=>{try{setTasks(await listAiTasks());}catch(error){toast.error(error instanceof Error?error.message:'Could not load AI tasks');}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
  const create=async(event:FormEvent)=>{event.preventDefault();const schedule=form.schedule_type==='manual'?null:form.schedule_type as Exclude<AiScheduleType,null>;if(schedule&&!form.next_run_at){toast.error('Choose the first date and time for this scheduled task.');return;}try{await createAiTask({title:form.title.trim(),instruction:form.instruction.trim(),schedule_type:schedule,next_run_at:schedule?new Date(form.next_run_at).toISOString():null,timezone:form.timezone});setForm({title:'',instruction:'',schedule_type:'manual',next_run_at:'',timezone:'Africa/Nairobi'});toast.success('AI task created.');await load();}catch(error){toast.error(error instanceof Error?error.message:'Could not create task');}};
  const runNow=async(task:AiTask)=>{setBusyId(task.id);try{const run=await runAiTaskNow(task.id);setRuns(items=>[run,...items.filter(item=>item.id!==run.id)]);setSelectedTask(task.id);if(run.status==='failed')toast.error(run.error_message||'Task run failed.');else toast.success('AI prepared the task output.');await load();}catch(error){toast.error(error instanceof Error?error.message:'Could not run task');}finally{setBusyId(null);}};
  const changeStatus=async(task:AiTask,status:AiTask['status'])=>{setBusyId(task.id);try{await updateAiTask(task.id,{status});toast.success(`Task ${status}.`);await load();}catch(error){toast.error(error instanceof Error?error.message:'Could not update task');}finally{setBusyId(null);}};
  const showRuns=async(task:AiTask)=>{setSelectedTask(task.id);try{setRuns(await listAiTaskRuns(task.id));}catch(error){toast.error(error instanceof Error?error.message:'Could not load run history');}};
  const retry=async(run:AiTaskRun)=>{setBusyId(run.id);try{const next=await retryAiTaskRun(run.id);setRuns(items=>[next,...items]);if(next.status==='failed')toast.error(next.error_message||'Retry failed.');else toast.success('Retry prepared new output.');await load();}catch(error){toast.error(error instanceof Error?error.message:'Could not retry task run');}finally{setBusyId(null);}};
  const reviewRun=async(run:AiTaskRun,decision:'approve'|'dismiss')=>{setBusyId(run.id);try{const updated=decision==='approve'?await approveAiTaskRun(run.id):await dismissAiTaskRun(run.id);setRuns(items=>items.map(item=>item.id===updated.id?updated:item));toast.success(decision==='approve'?'Output approved for admin use.':'Task output dismissed.');}catch(error){toast.error(error instanceof Error?error.message:'Could not review task output');}finally{setBusyId(null);}};

  return <AdminLayout title="Family Pledge AI Scheduled Tasks" subtitle="Prepare recurring admin work at the date, time and cadence your team chooses.">
    <div className="mb-4 flex flex-wrap gap-2"><Link href="/ai-assistant" className="btn-secondary inline-flex items-center gap-2"><ArrowLeft size={15}/>Draft workspace</Link><Link href="/ai/chat" className="btn-secondary inline-flex items-center gap-2"><Bot size={15}/>AI Chat</Link><Link href="/operations" className="btn-secondary">Operations</Link></div>
    <div className="mb-4 flex flex-wrap gap-2">{QUICK_TASKS.map(item=><button key={item.title} type="button" onClick={()=>setForm(v=>({...v,title:item.title,instruction:item.instruction}))} className="rounded-full border bg-white px-3 py-1.5 text-xs font-semibold text-gray-600 hover:border-primary hover:text-primary">{item.title}</button>)}</div>
    <form onSubmit={create} className="card mb-5 grid gap-3 p-5 md:grid-cols-6"><div className="md:col-span-3"><label className="label">Task title</label><input required maxLength={255} className="input" placeholder="e.g. Friday campaign summary" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="md:col-span-1"><label className="label">Schedule</label><select className="input" value={form.schedule_type} onChange={e=>setForm({...form,schedule_type:e.target.value})}><option value="manual">Manual</option><option value="once">Once</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></div><div className="md:col-span-2"><label className="label">First run</label><input type="datetime-local" disabled={form.schedule_type==='manual'} required={form.schedule_type!=='manual'} className="input disabled:bg-gray-100" value={form.next_run_at} onChange={e=>setForm({...form,next_run_at:e.target.value})}/></div><div className="md:col-span-5"><label className="label">What should Family Pledge AI prepare?</label><textarea required rows={3} maxLength={4000} className="input" placeholder="Summarize this month's contribution status and active Gaza campaigns for admin review." value={form.instruction} onChange={e=>setForm({...form,instruction:e.target.value})}/></div><div className="md:col-span-1"><label className="label">Timezone</label><select className="input" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}><option value="Africa/Nairobi">Nairobi</option><option value="Asia/Kolkata">India</option><option value="UTC">UTC</option></select><button className="btn-primary w-full mt-3">Create task</button></div></form>
    <div className="card overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead><tr className="border-b bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><th className="p-3">Task</th><th className="p-3">Status</th><th className="p-3">Schedule</th><th className="p-3">Next run</th><th className="p-3">Last run</th><th className="p-3">Controls</th></tr></thead><tbody>{tasks.map(task=><tr className="border-b align-top" key={task.id}><td className="p-3 max-w-sm"><b>{task.title}</b><div className="mt-1 text-xs leading-5 text-gray-500">{task.instruction}</div></td><td className="p-3"><Status value={task.status}/></td><td className="p-3 capitalize">{task.schedule_type||'Manual'}<div className="text-[11px] text-gray-400">{task.timezone}</div></td><td className="p-3 text-xs text-gray-500">{task.next_run_at?new Date(task.next_run_at).toLocaleString():'—'}</td><td className="p-3 text-xs text-gray-500">{task.last_run_at?new Date(task.last_run_at).toLocaleString():'Never'}</td><td className="p-3"><div className="flex flex-wrap gap-1.5"><button disabled={busyId===task.id||task.status==='cancelled'} className="btn-secondary inline-flex items-center gap-1 text-xs" onClick={()=>void runNow(task)}><Play size={12}/>Run now</button>{task.status==='active'&&<button disabled={busyId===task.id} className="btn-ghost inline-flex items-center gap-1 text-xs" onClick={()=>void changeStatus(task,'paused')}><Pause size={12}/>Pause</button>}{(task.status==='paused'||task.status==='draft')&&<button disabled={busyId===task.id} className="btn-ghost inline-flex items-center gap-1 text-xs" onClick={()=>void changeStatus(task,'active')}><Play size={12}/>Resume</button>}{task.status!=='cancelled'&&<button disabled={busyId===task.id} className="btn-ghost inline-flex items-center gap-1 text-xs text-red-600" onClick={()=>void changeStatus(task,'cancelled')}><XCircle size={12}/>Cancel</button>}<button className="btn-ghost inline-flex items-center gap-1 text-xs" onClick={()=>void showRuns(task)}><History size={12}/>History</button></div></td></tr>)}</tbody></table>{!loading&&!tasks.length&&<p className="p-8 text-center text-gray-500">No AI tasks yet.</p>}{loading&&<p className="p-8 text-center text-gray-400">Loading tasks…</p>}</div>
    {selectedTask&&<div className="card mt-5 p-5"><div className="mb-4 flex items-center justify-between gap-2"><div><h2 className="font-bold text-gray-900">Task run history</h2><p className="text-xs text-gray-500">Review generated work and the database context tools used.</p></div><button className="btn-ghost" onClick={()=>{setSelectedTask(null);setRuns([]);}}>Close</button></div><div className="space-y-3">{runs.map(run=><div key={run.id} className="rounded-xl border border-gray-200 p-4"><div className="mb-3 flex flex-wrap items-center gap-2 text-xs"><Status value={run.status}/><span className="text-gray-400">{new Date(run.executed_at||run.created_at).toLocaleString()}</span>{Array.isArray(run.generated_output?.context_used)&&run.generated_output!.context_used!.map(tool=><span key={tool} className="rounded-full bg-gray-100 px-2 py-1 text-gray-600">{tool.replace(/_/g,' ')}</span>)}</div>{run.generated_output?.text&&<pre className="whitespace-pre-wrap rounded-lg bg-gray-50 p-3 font-sans text-sm leading-6 text-gray-800">{run.generated_output.text}</pre>}{run.error_message&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{run.error_message}</div>}<div className="mt-3 flex flex-wrap gap-2">{run.status==='waiting_approval'&&<><button disabled={busyId===run.id} onClick={()=>void reviewRun(run,'approve')} className="btn-primary inline-flex items-center gap-1.5 text-xs"><CheckCircle2 size={13}/>Approve output</button><button disabled={busyId===run.id} onClick={()=>void reviewRun(run,'dismiss')} className="btn-ghost inline-flex items-center gap-1.5 text-xs text-red-600"><Ban size={13}/>Dismiss</button></>}{run.status==='validated'&&<span className="text-xs font-semibold text-green-700">Human-reviewed</span>}{run.status==='failed'&&<button disabled={busyId===run.id} onClick={()=>void retry(run)} className="btn-secondary inline-flex items-center gap-1.5 text-xs"><RotateCcw size={12}/>Retry</button>}</div></div>)}{!runs.length&&<p className="py-6 text-center text-sm text-gray-500">No runs for this task yet.</p>}</div></div>}
  </AdminLayout>;
}

function Status({value}:{value:string}){const cls=value==='active'||value==='waiting_approval'||value==='executed'||value==='validated'?'bg-green-100 text-green-700':value==='failed'||value==='cancelled'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700';return <span className={`inline-flex rounded-full px-2 py-1 text-[11px] font-semibold capitalize ${cls}`}>{value.replace(/_/g,' ')}</span>}
