'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Plus, Search, Sparkles, UserPlus } from 'lucide-react';
import Link from 'next/link';
import toast from 'react-hot-toast';
import AdminLayout from '../../components/AdminLayout';
import StatusBadge from '../../components/StatusBadge';
import { createTrackedContact, getTrackedContacts } from '../../lib/api';
import type { TrackedContact } from '../../types';

export default function ProspectsPage() {
  const [items,setItems]=useState<TrackedContact[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[showAdd,setShowAdd]=useState(false);
  const[form,setForm]=useState({full_name:'',phone:'',email:'',country:'',status:'following_up' as TrackedContact['status'],notes:'',referral_code:''});
  const load=async()=>{setLoading(true);try{setItems(await getTrackedContacts());}catch(e){toast.error(e instanceof Error?e.message:'Could not load follow-up register.');}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>items.filter(item=>{const text=`${item.full_name} ${item.phone||''} ${item.email||''} ${item.country||''} ${item.referral_code||''}`.toLowerCase();return(!search||text.includes(search.toLowerCase()))&&(!status||item.status===status);}),[items,search,status]);
  const submit=async(e:FormEvent)=>{e.preventDefault();try{const created=await createTrackedContact({...form,referral_code:form.referral_code.trim()||undefined});setItems(v=>[created,...v]);setForm({full_name:'',phone:'',email:'',country:'',status:'following_up',notes:'',referral_code:''});setShowAdd(false);toast.success('Person added to follow-up register.');}catch(error){toast.error(error instanceof Error?error.message:'Could not save person.');}};

  return <AdminLayout title="Prospects & Follow-up Register" subtitle="Keep pre-registration outreach separate from the registered donor database.">
    <div className="mb-5 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900"><b>This register is for people the team is still following up.</b> Once a person registers using their referral code, the linked account appears in the main Donor Manager.</div>
    <div className="card p-4 mb-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone, email, country or referral code…" className="input pl-9"/></div><select className="input sm:w-44" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="following_up">Following up</option><option value="pledged">Pledged</option><option value="paid">Paid</option><option value="paused">Paused</option></select><button onClick={()=>setShowAdd(v=>!v)} className="btn-primary inline-flex items-center gap-2"><Plus size={15}/>Add person</button></div>
      {showAdd&&<form onSubmit={submit} className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-3"><input required className="input" placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input className="input" placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="input" placeholder="Country" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/><input className="input uppercase" placeholder="Referral code, e.g. AMINA24" value={form.referral_code} onChange={e=>setForm({...form,referral_code:e.target.value.toUpperCase()})}/><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value as TrackedContact['status']})}><option value="following_up">Following up</option><option value="pledged">Pledged</option><option value="paid">Paid</option><option value="paused">Paused</option></select><textarea className="input md:col-span-2" rows={2} placeholder="Private follow-up notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="btn-primary inline-flex items-center justify-center gap-2"><UserPlus size={15}/>Save person</button></form>}
    </div>
    <div className="mb-3 flex flex-wrap justify-between gap-2 text-xs text-gray-500"><span>{filtered.length.toLocaleString()} visible records</span><div className="flex gap-2"><Link href="/donors" className="btn-secondary">Registered donors</Link><Link href="/ai/chat" className="btn-secondary inline-flex items-center gap-2"><Sparkles size={14}/>Ask AI for follow-up planning</Link></div></div>
    <div className="card overflow-hidden"><div className="overflow-x-auto max-h-[65vh]"><table className="w-full min-w-[900px] text-sm"><thead className="sticky top-0 bg-gray-50 border-b"><tr className="text-left text-xs uppercase text-gray-400"><th className="p-3">Name</th><th className="p-3">Contact</th><th className="p-3">Country</th><th className="p-3">Referral</th><th className="p-3">Status</th><th className="p-3">Notes</th><th className="p-3">Account</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-12 text-center text-gray-400">Loading follow-up register…</td></tr>:filtered.map(item=><tr key={item.id} className="border-b align-top"><td className="p-3 font-semibold text-gray-900">{item.full_name}</td><td className="p-3"><div>{item.phone||'—'}</div><div className="text-xs text-gray-400">{item.email||''}</div></td><td className="p-3">{item.country||'—'}</td><td className="p-3 font-mono text-xs">{item.referral_code||'—'}</td><td className="p-3"><StatusBadge status={item.status}/></td><td className="p-3 max-w-sm text-gray-600">{item.notes||'—'}</td><td className="p-3">{item.linked_user_id?<span className="text-xs font-bold text-green-700">Registered ✓</span>:<span className="text-xs text-gray-400">Not yet</span>}</td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={7} className="p-12 text-center text-gray-400">No records match this view.</td></tr>}</tbody></table></div></div>
  </AdminLayout>;
}
