'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Plus, Edit2, Eye, EyeOff, RefreshCw, Sparkles } from 'lucide-react';
import AdminLayout from '../../components/AdminLayout';
import MediaUrlInput from '../../components/MediaUrlInput';
import { getImpactCards, createImpactCard, updateImpactCard } from '../../lib/api';
import { ImpactCard } from '../../types';
import { formatDate } from '../../lib/utils';
import toast from 'react-hot-toast';

type ModalMode = 'create' | 'edit' | null;
interface ImpactForm { title:string;story:string;beneficiaries_count:string;location:string;image_url:string;video_url:string;completed_date:string;published:boolean; }
const EMPTY:ImpactForm={title:'',story:'',beneficiaries_count:'',location:'',image_url:'',video_url:'',completed_date:'',published:false};

export default function ImpactPage() {
  const [cards,setCards]=useState<ImpactCard[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
  const[modalMode,setModalMode]=useState<ModalMode>(null);const[editItem,setEditItem]=useState<ImpactCard|null>(null);const[form,setForm]=useState<ImpactForm>(EMPTY);const[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setCards(await getImpactCards());}catch(e){setCards([]);setError(e instanceof Error?e.message:'Could not load impact updates.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const openCreate=()=>{setEditItem(null);setForm(EMPTY);setModalMode('create');};
  const openEdit=(item:ImpactCard)=>{setEditItem(item);setForm({title:item.title,story:item.story,beneficiaries_count:item.beneficiaries_count?.toString()||'',location:item.location||'',image_url:item.image_url||'',video_url:item.video_url||'',completed_date:item.completed_date||'',published:item.published});setModalMode('edit');};
  const closeModal=()=>{setModalMode(null);setEditItem(null);};
  const handleSave=async()=>{if(!form.title.trim()||!form.story.trim()){toast.error('Title and story are required.');return;}setSaving(true);const payload:Partial<ImpactCard>={title:form.title.trim(),story:form.story.trim(),beneficiaries_count:form.beneficiaries_count?parseInt(form.beneficiaries_count):undefined,location:form.location||undefined,image_url:form.image_url||undefined,video_url:form.video_url||undefined,completed_date:form.completed_date||undefined,published:form.published};try{if(modalMode==='create')await createImpactCard(payload);else if(editItem)await updateImpactCard(editItem.id,payload);toast.success(modalMode==='create'?'Impact update created.':'Impact update saved.');closeModal();await load();}catch(e){toast.error(e instanceof Error?e.message:'Could not save impact update. Nothing was published.');}finally{setSaving(false);}};
  const togglePublish=async(item:ImpactCard)=>{try{const updated=await updateImpactCard(item.id,{published:!item.published});setCards(v=>v.map(c=>c.id===updated.id?updated:c));toast.success(updated.published?'Published to donor app.':'Removed from donor app.');}catch(e){toast.error(e instanceof Error?e.message:'Could not change publish state.');}};

  return <AdminLayout title="Impact Studio" subtitle="Turn verified Family Pledge work into clear, media-rich impact updates for donors.">
    <div className="mb-5 flex flex-wrap justify-end gap-2"><button onClick={()=>void load()} className="btn-secondary inline-flex items-center gap-2"><RefreshCw size={15}/>Refresh</button><Link href="/ai-assistant" className="btn-secondary inline-flex items-center gap-2"><Sparkles size={15}/>Draft impact story with AI</Link><button onClick={openCreate} className="btn-primary flex items-center gap-2"><Plus size={16}/>New Impact Update</button></div>
    {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error} <button onClick={()=>void load()} className="ml-2 font-semibold underline">Retry</button></div>}
    {loading?<div className="grid grid-cols-1 md:grid-cols-2 gap-4">{[1,2,3].map(i=><div key={i} className="card p-5 h-48 animate-pulse bg-gray-100"/>)}</div>:<div className="grid grid-cols-1 md:grid-cols-2 gap-4">{cards.map(card=><div key={card.id} className="card overflow-hidden">{card.image_url&&<img src={card.image_url} alt="" className="h-40 w-full object-cover"/>}<div className="p-5"><div className="flex items-start justify-between mb-3"><div className="flex-1 min-w-0 mr-3"><h3 className="font-bold text-gray-900 leading-snug">{card.title}</h3><div className="text-xs text-gray-400 mt-1 flex flex-wrap gap-3">{card.location&&<span>{card.location}</span>}{card.beneficiaries_count!==undefined&&<span>{card.beneficiaries_count.toLocaleString()} beneficiaries</span>}<span>{formatDate(card.created_at)}</span></div></div><div className="flex gap-1 flex-shrink-0"><button onClick={()=>void togglePublish(card)} title={card.published?'Unpublish':'Publish'} className={`p-1.5 rounded ${card.published?'bg-green-50 text-green-600':'bg-gray-50 text-gray-400'}`}>{card.published?<Eye size={14}/>:<EyeOff size={14}/>}</button><button onClick={()=>openEdit(card)} className="p-1.5 rounded bg-blue-50 text-blue-600"><Edit2 size={14}/></button></div></div><p className="text-sm text-gray-600 leading-relaxed line-clamp-4">{card.story}</p>{card.video_url&&<div className="mt-2 text-xs font-semibold text-primary">Video attached</div>}{!card.published&&<span className="inline-block mt-3 px-2 py-0.5 text-xs bg-amber-100 text-amber-700 rounded font-medium">Draft — not visible to donors</span>}</div></div>)}{cards.length===0&&<div className="md:col-span-2 card p-10 text-center text-gray-400">No impact updates yet.</div>}</div>}
    {modalMode&&<div className="modal-shell"><div className="modal-panel"><h3 className="text-lg font-bold text-gray-900 mb-4">{modalMode==='create'?'Create Impact Update':'Edit Impact Update'}</h3><div className="space-y-4"><div><label className="label">Title *</label><input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} className="input" placeholder="e.g. Food packages reached families in Gaza"/></div><div><label className="label">Verified Story *</label><textarea value={form.story} onChange={e=>setForm(f=>({...f,story:e.target.value}))} className="input" rows={5} placeholder="Write only verified impact facts and the human story…"/></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Beneficiaries</label><input type="number" min={0} value={form.beneficiaries_count} onChange={e=>setForm(f=>({...f,beneficiaries_count:e.target.value}))} className="input"/></div><div><label className="label">Location</label><input value={form.location} onChange={e=>setForm(f=>({...f,location:e.target.value}))} className="input" placeholder="e.g. Gaza"/></div></div><MediaUrlInput label="Impact Cover" value={form.image_url} onChange={v=>setForm(f=>({...f,image_url:v}))} accept={['r2']} uploadFolder="impact" relatedEntityType="impact" relatedEntityId={editItem?.id}/><MediaUrlInput label="Video" value={form.video_url} onChange={v=>setForm(f=>({...f,video_url:v}))} accept={['r2','youtube']} showPreview={false} uploadFolder="impact" relatedEntityType="impact" relatedEntityId={editItem?.id} onUploaded={media=>{if(media.thumbnail_url)setForm(f=>({...f,image_url:media.thumbnail_url!}));}} hint="Videos use the existing Cloudflare Stream flow when uploaded."/><div><label className="label">Completion Date</label><input type="date" value={form.completed_date} onChange={e=>setForm(f=>({...f,completed_date:e.target.value}))} className="input"/></div><label className="flex items-center gap-3 cursor-pointer"><input type="checkbox" checked={form.published} onChange={e=>setForm(f=>({...f,published:e.target.checked}))} className="w-4 h-4 accent-primary"/><span className="text-sm text-gray-700">Publish after this save succeeds</span></label><div className="modal-actions"><button onClick={()=>void handleSave()} disabled={saving} className="btn-primary flex-1">{saving?'Saving…':'Save'}</button><button onClick={closeModal} className="btn-ghost">Cancel</button></div></div></div></div>}
  </AdminLayout>;
}
