import { Dashboard, Campaign, ImpactCard, Reminder, NamlefContent, Pledge, CollectorDashboard, User } from '../types';

export const MOCK_USER: User = {
  id: 'mock-user-1',
  full_name: 'Ahmed Hassan',
  nickname: 'Abu Yusuf',
  phone: '+254700000001',
  email: 'ahmed@example.com',
  country: 'Kenya',
  city: 'Nairobi',
  anonymous_publicly: false,
  is_collector: true,
  pledge_status: 'paid',
  donor_number: 42,
  badges: [
    { id: '1', name: 'First Pledge', description: 'Made your first pledge', icon: 'heart', tier: 'bronze', earned_at: '2024-01-15' },
    { id: '2', name: 'Faithful Donor', description: '3 consecutive months', icon: 'ribbon', tier: 'silver', earned_at: '2024-04-01' },
  ],
  created_at: '2024-01-10T10:00:00Z',
};

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Sign the Family Pledge',
    description: 'Families can sign for free or commit USD 10 monthly for a year, then receive awareness materials that keep Palestine present in every home.',
    type: 'monthly',
    campaign_type: 'monthly',
    target_donors: 25048,
    current_donors: 18420,
    donor_target: 25048,
    donor_count: 18420,
    target_amount: 250480,
    raised_amount: 184200,
    is_active: true,
    is_urgent: false,
    start_date: '2026-01-01',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'camp-2',
    title: 'Awareness Bags for Every Home',
    description: 'Deliver books, videos, podcasts, comics, cards, articles, and games that connect families emotionally and ideologically to Jerusalem and Al-Aqsa.',
    type: 'general',
    campaign_type: 'general',
    target_donors: 5000,
    current_donors: 3125,
    donor_target: 5000,
    donor_count: 3125,
    target_amount: 50000,
    raised_amount: 31250,
    is_active: true,
    is_urgent: false,
    start_date: '2026-02-01',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'camp-3',
    title: 'Support Women-Headed Families',
    description: 'Support the steadfastness of Palestinian women who carry their families through siege, displacement, and loss.',
    type: 'sponsorship',
    campaign_type: 'sponsorship',
    target_donors: 1000,
    current_donors: 642,
    donor_target: 1000,
    donor_count: 642,
    target_amount: 100000,
    raised_amount: 64200,
    is_active: true,
    is_urgent: true,
    start_date: '2026-03-01',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'camp-4',
    title: 'Plant a Tree in My Name',
    description: 'A symbolic project from the Family Pledge website that turns each pledge into a living reminder of Palestine, resilience, and hope.',
    type: 'general',
    campaign_type: 'general',
    target_donors: 3000,
    current_donors: 1480,
    donor_target: 3000,
    donor_count: 1480,
    target_amount: 30000,
    raised_amount: 14800,
    is_active: true,
    is_urgent: false,
    start_date: '2026-04-01',
    created_at: '2026-04-01T00:00:00Z',
  },
];

export const MOCK_IMPACT_CARDS: ImpactCard[] = [
  {
    id: 'impact-1',
    title: 'Family Awareness Bags Prepared',
    description: 'Books, cards, videos, podcasts, articles, and family activities prepared to help parents teach children about Palestine, Jerusalem, and Al-Aqsa at home.',
    story: 'Each awareness bag is designed to make the Palestinian cause part of family conversations, not a distant headline.',
    category: 'education',
    beneficiaries: 3200,
    beneficiaries_count: 3200,
    location: 'Global pledge families',
    date: '2026-06-25',
  },
  {
    id: 'impact-2',
    title: 'Women-Headed Families Supported',
    description: 'Monthly pledge contributions help strengthen Palestinian women who are holding their families together through displacement and hardship.',
    story: 'The project focuses on dignity, stability, and consistent family support.',
    category: 'widows',
    beneficiaries: 640,
    beneficiaries_count: 640,
    location: 'Palestine',
    date: '2026-06-20',
  },
  {
    id: 'impact-3',
    title: 'Pledge Community Passed 25k Signatures',
    description: 'Families from multiple countries are joining the pledge community, signing for free or committing to monthly support.',
    story: 'Every signature is a promise that Palestine remains present in the home.',
    category: 'community',
    beneficiaries: 25048,
    beneficiaries_count: 25048,
    location: 'Worldwide',
    date: '2026-06-18',
  },
  {
    id: 'impact-4',
    title: 'Children’s Palestine Learning Activities',
    description: 'Child-friendly games, cards, and comics help Muslim families connect children emotionally to Jerusalem, Al-Aqsa, and Palestinian culture.',
    story: 'Beautiful learning moments help children understand why the pledge matters.',
    category: 'children',
    beneficiaries: 1800,
    beneficiaries_count: 1800,
    location: 'Family homes',
    date: '2026-06-10',
  },
];

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    type: 'motivation',
    title: 'Keep Palestine Present at Home',
    text: 'One small family conversation today can keep the Palestinian cause alive in the hearts of our children.',
    translation: 'Read one card, watch one short video, or make one dua together as a family.',
    explanation: 'Family Pledge is not only a donation flow; it is a rhythm of awareness, dua, and steady support.',
    date: '2026-06-30',
  },
  {
    id: 'rem-2',
    type: 'sadaqah',
    title: 'A Consistent Monthly Pledge',
    text: 'If you are able, renew your USD 10 pledge this month and invite one family to join.',
    translation: 'Small consistent giving becomes strong collective support.',
    explanation: 'Users may also sign for free and still receive awareness materials and reminders.',
    date: '2026-06-29',
  },
  {
    id: 'rem-3',
    type: 'dua',
    title: 'Family Dua for Palestine',
    arabic_text: 'اللَّهُمَّ احْفَظْ أَهْلَ فِلَسْطِين',
    text: 'O Allah, protect the people of Palestine, strengthen their families, and grant them relief.',
    translation: 'Make this dua together after salah or before sleeping.',
    explanation: 'The website centres the pledge around families; the app should help the whole family remember Palestine daily.',
    source_reference: 'Daily family dua',
    date: '2026-06-28',
  },
  {
    id: 'rem-4',
    type: 'friday',
    title: 'Friday Family Challenge',
    text: 'This Friday, share your pledge link with three families and help grow the community of support.',
    translation: 'Awareness spreads family to family.',
    explanation: 'Motivating referrals and collectors should feel positive, warm, and mission-led.',
    date: '2026-06-27',
  },
  {
    id: 'rem-5',
    type: 'motivation',
    title: 'Jerusalem and Al-Aqsa in Our Hearts',
    text: 'Teach one child one beautiful fact about Jerusalem or Al-Aqsa today.',
    translation: 'Culture, memory, and faith are part of the pledge.',
    explanation: 'This mirrors the Family Pledge goal of connecting Muslim families emotionally and ideologically to Jerusalem and Al-Aqsa.',
    date: '2026-06-26',
  },
];

export const MOCK_NAMLEF_CONTENT: NamlefContent[] = [
  {
    id: 'namlef-1',
    type: 'about',
    title: 'About Family Pledge with NAMLEF',
    content: 'Family Pledge is a family covenant to support Palestinian families, keep the Palestinian cause alive at home, and give consistently through NAMLEF Gaza Family Support. Families can sign for free or contribute monthly, then receive reminders and awareness content for parents and children.',
    author: 'NAMLEF Secretariat',
    author_title: 'National Muslim Leaders Forum',
    date: '2026-01-01',
  },
  {
    id: 'namlef-2',
    type: 'introduction',
    title: 'What You Receive After Signing',
    content: 'After signing, families receive awareness materials inspired by the main website: books, videos, podcasts, comics, cards, articles, games, and monthly reminders that keep Palestine present in every home.',
    date: '2026-01-15',
  },
  {
    id: 'namlef-3',
    type: 'voice_of_support',
    title: 'Voice of Support: Parklands Mosque',
    content: 'Palestine is a trust. We invite families to join the pledge, contribute consistently if able, and encourage others with mercy, dignity, and sincerity.',
    author: 'Sheikh Abdur Rahman Ishaq',
    author_title: 'Imam of Parklands Mosque, Nairobi',
    date: '2026-06-01',
  },
  {
    id: 'namlef-4',
    type: 'sheikh_message',
    title: 'Why This Pledge Matters',
    content: 'Supporting the Palestinian woman who provides for her family is support for the resilience of the whole Palestinian family. Every pledge strengthens awareness, dignity, and steady relief.',
    author: 'Family Pledge Partners',
    author_title: 'Global supporters of Jerusalem and Palestine',
    date: '2026-06-10',
  },
];

export const MOCK_PLEDGE_STATUS = {
  pledge: {
    id: 'pledge-001',
    user_id: 'mock-user-1',
    amount: 10,
    currency: 'USD',
    status: 'paid' as const,
    month: 'June',
    year: 2025,
    contributed_at: '2025-06-05T09:30:00Z',
    reference: 'QKR7XNPK',
  },
  history: [
    { id: 'p1', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'June', year: 2025, contributed_at: '2025-06-05T09:30:00Z', reference: 'QKR7XNPK' },
    { id: 'p2', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'May', year: 2025, contributed_at: '2025-05-03T11:00:00Z', reference: 'MPF3BWKL' },
    { id: 'p3', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'April', year: 2025, contributed_at: '2025-04-07T08:15:00Z', reference: 'TXN9923X' },
    { id: 'p4', user_id: 'u1', amount: 10, currency: 'USD', status: 'missed' as const, month: 'March', year: 2025 },
    { id: 'p5', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'February', year: 2025, contributed_at: '2025-02-10T14:00:00Z', reference: 'BWK229JK' },
    { id: 'p6', user_id: 'u1', amount: 10, currency: 'USD', status: 'paid' as const, month: 'January', year: 2025, contributed_at: '2025-01-12T10:00:00Z', reference: 'INV00142' },
  ],
};

export const MOCK_DASHBOARD: Dashboard = {
  user: MOCK_USER,
  pledge_status: 'paid',
  donor_number: 42,
  total_donors_today: 178,
  active_campaign: MOCK_CAMPAIGNS[0],
  emergency_appeal: MOCK_CAMPAIGNS[1],
  latest_reminder: MOCK_REMINDERS[0],
  latest_impact: MOCK_IMPACT_CARDS[0],
  monthly_progress: {
    target: 1000,
    current: 634,
  },
};

export const MOCK_COLLECTOR: CollectorDashboard = {
  collector_code: 'AHM-KE42',
  total_registered: 15,
  contributed_this_month: 10,
  pending_this_month: 5,
  invite_link: 'https://familypledge.org/join?code=AHM-KE42',
  circle_members: [
    { id: 'm1', display_name: 'Yusuf Omar', pledge_status: 'paid', joined_at: '2025-01-15T10:00:00Z' },
    { id: 'm2', display_name: 'Khadija Said', pledge_status: 'paid', joined_at: '2025-02-01T09:00:00Z' },
    { id: 'm3', display_name: 'Ibrahim Khalid', pledge_status: 'pending', joined_at: '2025-02-10T12:00:00Z' },
    { id: 'm4', display_name: 'Maryam Hassan', pledge_status: 'paid', joined_at: '2025-03-05T08:00:00Z' },
    { id: 'm5', display_name: 'Anon Donor', pledge_status: 'missed', joined_at: '2025-03-12T11:00:00Z' },
    { id: 'm6', display_name: 'Aisha Noor', pledge_status: 'paid', joined_at: '2025-04-01T14:00:00Z' },
    { id: 'm7', display_name: 'Bilal Ahmad', pledge_status: 'pending', joined_at: '2025-04-20T10:00:00Z' },
    { id: 'm8', display_name: 'Zaynab Juma', pledge_status: 'paid', joined_at: '2025-05-03T09:30:00Z' },
  ],
};
